/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewDosen;

import connectionConfig.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ferdy Yoga
 */
public class NilaiUjian extends javax.swing.JFrame {
    DefaultTableModel model = new DefaultTableModel();
    Koneksi kon = new Koneksi();
    Connection con = (Connection) kon.configDB();

    
    public NilaiUjian() {
        initComponents();
        tabelmhs.setModel(model);
        model.addColumn("id");
        model.addColumn("Nama");
        model.addColumn("Tingkat keberhasilan");
        model.addColumn("Penulisan buku laporan");
        model.addColumn("Keaktifan mahasiswa");
        
        loadTable();
        comboList();
        id.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pilihnama = new javax.swing.JComboBox<>();
        tgktkeberhasilan = new javax.swing.JTextField();
        penulisanbukulaporan = new javax.swing.JTextField();
        keaktifanmahasiswa = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        tambah = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelmhs = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama ");

        jLabel2.setText("Tingkat keberhasilan aplikasi / Pemahaman tugas PKN");

        jLabel3.setText("Penulisan buku laporan");

        jLabel4.setText("Keaktifan mahasiswa");

        pilihnama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih nama" }));

        tgktkeberhasilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgktkeberhasilanActionPerformed(evt);
            }
        });
        tgktkeberhasilan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tgktkeberhasilanKeyTyped(evt);
            }
        });

        penulisanbukulaporan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                penulisanbukulaporanKeyTyped(evt);
            }
        });

        keaktifanmahasiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keaktifanmahasiswaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(keaktifanmahasiswa, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(penulisanbukulaporan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tgktkeberhasilan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pilihnama, 0, 87, Short.MAX_VALUE))
                .addGap(204, 204, 204))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(pilihnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tgktkeberhasilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(penulisanbukulaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(keaktifanmahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tambah.setBackground(new java.awt.Color(0, 204, 204));
        tambah.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tambah.setForeground(new java.awt.Color(0, 153, 153));
        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(0, 204, 204));
        edit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        edit.setForeground(new java.awt.Color(0, 153, 153));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(0, 204, 204));
        hapus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        hapus.setForeground(new java.awt.Color(0, 153, 153));
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 204, 204));
        back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        back.setForeground(new java.awt.Color(0, 153, 153));
        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabelmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelmhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelmhs);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Nilai Ujian");

        id.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(105, 105, 105)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(id))
                .addGap(32, 32, 32))
        );

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(reset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        try {
            int keberhasilan = Integer.parseInt(tgktkeberhasilan.getText());
            int laporan = Integer.parseInt(penulisanbukulaporan.getText());
            int keaktifan = Integer.parseInt(keaktifanmahasiswa.getText());

            String sql = "insert into nilai_ujian (nama,keberhasilan, penulisan, keaktifan)"
                    + "VALUES ('"+pilihnama.getSelectedItem()+"','" + keberhasilan + "', '" + laporan + "', '" + keaktifan + "')";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
             ps.close();
             reset.doClick();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data gagal" + e);
        }
        loadTable();
        comboList();
    }//GEN-LAST:event_tambahActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
            int keberhasilan = Integer.parseInt(tgktkeberhasilan.getText());
            int laporan = Integer.parseInt(penulisanbukulaporan.getText());
            int keaktifan = Integer.parseInt(keaktifanmahasiswa.getText());
            

            String sql = "update nilai_ujian set keberhasilan = '"+keberhasilan +"', penulisan = '"+laporan + "', keaktifan = '"+ keaktifan +"'"
                    + "where id_ujian = '"+id.getText()+"'";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
             ps.close();
             reset.doClick();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data gagal" + e);
        }
        loadTable();
        comboList();
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        String mahasiswa = id.getText();
        if(tabelmhs.isRowSelected(tabelmhs.getSelectedRow())){
            try {
                String sql = "delete from nilai_ujian where id_ujian = '"+mahasiswa+"'";
                PreparedStatement ps = con.prepareCall(sql);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Succesfully Deleted");
                ps.close();
                reset.doClick(); 
            } catch (Exception e) {
            }
        }
        loadTable();

    }//GEN-LAST:event_hapusActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        pilihnama.setSelectedItem("Pilih nama");
        tgktkeberhasilan.setText("");
        penulisanbukulaporan.setText("");
        keaktifanmahasiswa.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void tabelmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelmhsMouseClicked
       int tabel = tabelmhs.getSelectedRow();
       
       String a = tabelmhs.getValueAt(tabel, 0).toString();
        id.setText(a);
        
        String b = tabelmhs.getValueAt(tabel, 2).toString();
        tgktkeberhasilan.setText(b);
        
         String c = tabelmhs.getValueAt(tabel, 3).toString();
        penulisanbukulaporan.setText(c);
        
        String d = tabelmhs.getValueAt(tabel, 4).toString();
        keaktifanmahasiswa.setText(d);
    }//GEN-LAST:event_tabelmhsMouseClicked

    private void tgktkeberhasilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgktkeberhasilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgktkeberhasilanActionPerformed

    private void tgktkeberhasilanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgktkeberhasilanKeyTyped
       char kar = evt.getKeyChar();
        if (!(Character.isDigit(kar))) {
            JOptionPane.showMessageDialog(null, "Hanya bisa menggunakan angka");
            evt.consume();
        }
    }//GEN-LAST:event_tgktkeberhasilanKeyTyped

    private void penulisanbukulaporanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_penulisanbukulaporanKeyTyped
        char kar = evt.getKeyChar();
        if (!(Character.isDigit(kar))) {
            JOptionPane.showMessageDialog(null, "Hanya bisa menggunakan angka");
            evt.consume();
        }
    }//GEN-LAST:event_penulisanbukulaporanKeyTyped

    private void keaktifanmahasiswaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keaktifanmahasiswaKeyTyped
       char kar = evt.getKeyChar();
        if (!(Character.isDigit(kar))) {
            JOptionPane.showMessageDialog(null, "Hanya bisa menggunakan angka");
            evt.consume();
        }
    }//GEN-LAST:event_keaktifanmahasiswaKeyTyped

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        DashboardDosen dosen = new DashboardDosen();
        dosen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NilaiUjian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NilaiUjian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NilaiUjian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NilaiUjian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NilaiUjian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField keaktifanmahasiswa;
    private javax.swing.JTextField penulisanbukulaporan;
    private javax.swing.JComboBox<String> pilihnama;
    private javax.swing.JButton reset;
    private javax.swing.JTable tabelmhs;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tgktkeberhasilan;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            String sql = "SELECT * FROM nilai_ujian";
            Statement n = con.createStatement();
            ResultSet rs = n.executeQuery(sql);

            while (rs.next()) {
                Object[] o = new Object[6];
                o[0] = rs.getString("id_ujian");
                o[1] = rs.getString("nama");
                o[2] = rs.getString("keberhasilan");
                o[3] = rs.getString("penulisan");
                o[4] = rs.getString("keaktifan");
                model.addRow(o);
            }
        } catch (SQLException e) {

        }

    }
    public void comboList(){
        try {
        String sql = "select nama from tb_mahasiswa where status = 'Diterima'";
        Statement s = con.createStatement();
        ResultSet rs = s.executeQuery(sql);
        
        while(rs.next()){
             Object[] o = new Object[3];
             o[0] = rs.getString("nama");
             pilihnama.addItem((String) o[0]);
        }
        rs.close();
    } catch (Exception e) {
    }

    }
}
