/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.controller_nilaiPerusahaan;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author LEGION
 */
public class TambahNilaiForm extends javax.swing.JFrame {

    controller_nilaiPerusahaan control;
    
    public TambahNilaiForm() throws SQLException {
        initComponents();
        control = new controller_nilaiPerusahaan(this);
        control.isiTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listNama = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sopan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        disHadir = new javax.swing.JTextField();
        disPeker = new javax.swing.JTextField();
        kePrak = new javax.swing.JTextField();
        tngjwb = new javax.swing.JTextField();
        mau = new javax.swing.JTextField();
        ilPrak = new javax.swing.JTextField();
        trampil = new javax.swing.JTextField();
        bicara = new javax.swing.JTextField();
        gaul = new javax.swing.JTextField();
        tbhBtn = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama :");

        listNama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Nama--", " " }));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel2.setText("Nilai Perusahaan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(310, 310, 310))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel3.setText("SOPAN SANTUN");

        jLabel4.setText("DISIPLIN DALAM PEKERJAAN");

        jLabel5.setText("DISIPLIN KEHADIRAN");

        jLabel6.setText("KEDUNGGUHAN DALAM MELAKUKAN KERJA PRAKTEK");

        jLabel7.setText("KEMAUAN UNTUK MELAKUKAN HAL-HAL YANG ADA  DI TEMPAT KERJA");

        jLabel8.setText("TANGGUNG JAWAB");

        jLabel9.setText("PENGETAHUAN TENTANG ILMU YANG DI LAKSANAKAN  DALAM KERJA PRAKTEK");

        jLabel10.setText("KETERAMPILAN");

        jLabel11.setText("KAMAUAN BERBICARA/MENYAMPAIKAN");

        jLabel12.setText(" KEMAUAN BERGAUL");

        disHadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disHadirActionPerformed(evt);
            }
        });

        tbhBtn.setText("Tambah");
        tbhBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbhBtnActionPerformed(evt);
            }
        });

        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bicara, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listNama, javax.swing.GroupLayout.Alignment.LEADING, 0, 167, Short.MAX_VALUE)
                    .addComponent(sopan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disHadir, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disPeker, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kePrak, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tngjwb, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mau, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ilPrak, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trampil, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gaul))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(39, 39, 39)
                .addComponent(tbhBtn)
                .addGap(307, 307, 307))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(listNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sopan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(disHadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(disPeker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kePrak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tngjwb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(mau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ilPrak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(trampil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(bicara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(gaul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbhBtn)
                    .addComponent(back))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disHadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disHadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disHadirActionPerformed

    private void tbhBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbhBtnActionPerformed
        control.insert();
        control.isiTabel();
        control.reset();
    }//GEN-LAST:event_tbhBtnActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       NilaiPerusahaan nilai;
        try {
            nilai = new NilaiPerusahaan();
            nilai.setVisible(true);
       this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TambahNilaiForm.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahNilaiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahNilaiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahNilaiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahNilaiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TambahNilaiForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TambahNilaiForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    public javax.swing.JTextField bicara;
    public javax.swing.JTextField disHadir;
    public javax.swing.JTextField disPeker;
    public javax.swing.JTextField gaul;
    public javax.swing.JTextField ilPrak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField kePrak;
    public javax.swing.JComboBox<String> listNama;
    public javax.swing.JTextField mau;
    public javax.swing.JTextField sopan;
    private javax.swing.JButton tbhBtn;
    public javax.swing.JTextField tngjwb;
    public javax.swing.JTextField trampil;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the back
     */
    public javax.swing.JButton getBack() {
        return back;
    }

    /**
     * @return the bicara
     */
    public javax.swing.JTextField getBicara() {
        return bicara;
    }

    /**
     * @return the disHadir
     */
    public javax.swing.JTextField getDisHadir() {
        return disHadir;
    }

    /**
     * @return the disPeker
     */
    public javax.swing.JTextField getDisPeker() {
        return disPeker;
    }

    /**
     * @return the gaul
     */
    public javax.swing.JTextField getGaul() {
        return gaul;
    }

    /**
     * @return the ilPrak
     */
    public javax.swing.JTextField getIlPrak() {
        return ilPrak;
    }

    /**
     * @return the kePrak
     */
    public javax.swing.JTextField getKePrak() {
        return kePrak;
    }

    /**
     * @return the listNama
     */
    public javax.swing.JComboBox<String> getListNama() {
        return listNama;
    }

    /**
     * @return the mau
     */
    public javax.swing.JTextField getMau() {
        return mau;
    }

    /**
     * @return the sopan
     */
    public javax.swing.JTextField getSopan() {
        return sopan;
    }

    /**
     * @return the tbhBtn
     */
    public javax.swing.JButton getTbhBtn() {
        return tbhBtn;
    }

    /**
     * @return the tngjwb
     */
    public javax.swing.JTextField getTngjwb() {
        return tngjwb;
    }

    /**
     * @return the trampil
     */
    public javax.swing.JTextField getTrampil() {
        return trampil;
    }

}
